### ISSUE TITLE
`VIDEO_URLS` for `DIM_ALLDAY_METADATA` are private and do not load

### ISSUE THREAD

**Issue by ltirrell** [FlipsideCrypto/flow-models#63]
The `VIDEO_URLS` for `DIM_ALLDAY_METADATA` are stored on Google Cloud, and are not publicly accessible. I'm unsure if there is another on-chain/API-based source for a URL that is publicly viewable.

However, it is possible to view videos on the NFL ALL DAY site. These can be constructed from parameters given in this table:

```sql
    moment_stats_full  ['id'] as id,
    lower(replace(set_name, ' ', '_')) as set_name_clean,
    concat(
        'https://assets.nflallday.com/editions/',
        set_name_clean,
        '/',
        id,
        '/play_',
        id,
        '_',
        set_name_clean,
        '_capture_AnimationCapture_Video_Square_Grey_1080_1080_Grey.mp4'
    ) as nflallday_assets_url
```

For example, this [Levi Wallace Moment](https://nflallday.com/listing/moment/745) (NFT_ID 1992250) has a video available [here](https://assets.nflallday.com/editions/super_wild_card_weekend/79a7bad3-4d53-41b6-99fe-293cd971f8e6/play_79a7bad3-4d53-41b6-99fe-293cd971f8e6_super_wild_card_weekend_capture_AnimationCapture_Video_Square_Grey_1080_1080_Grey.mp4).

I'm not sure if this is stable/resilient, but it would be nice to have videos available in some way!

Example query [here](https://app.flipsidecrypto.com/velocity/queries/72d21656-8ee0-4ce4-ae94-ccfde2b48302).

**Comment by forgxyz** [comment]
Thanks @ltirrell - these are in the metadata so Dapper must be blocking access to external viewers. Appreciate the code, I'll integrate the working URL in. It's nice to have.

**Comment by ltirrell** [comment]
the NFL marketplace site page may be better, and looks a lot less hacky. its
```python
f"https://nflallday.com/listing/moment/{x}"
```
where x is `moment_stats_full ['flowID']` from `flow.core.dim_allday_metadata`

**Comment by forgxyz** [comment]
🫡🌲

**Comment by forgxyz** [comment]
Sweet, we definitely want to expand [community contributions](https://docs.flipsidecrypto.com/our-data/contribute-to-flipside-data), in general.

**Comment by ltirrell** [comment]
This fell off my radar, but glad it was added!
